#baseURL: "https://www.digital-masterpiece.com"
languageCode: "en-us"
title: "Digital Masterpiece"
canonifyURLs: true
disableKinds: ["taxonomy", "taxonomyTerm"]
enableRobotsTXT: true
relativeURLs: true