# https://www.jacobtomlinson.co.uk/posts/2020/testing-static-sites-with-lighthouse-ci-and-github-actions/
name: Lighthouse Audit & Firebase Deployment
on:
  push:
    branches:
      - 'master'
jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.68.3"
          extended: true
      - name: Install NPM Dependencies
        run: npm install
      - name: Serve Site
        run: hugo server --environment=production --baseURL=http://localhost:1313 &
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: "./.github/config/lighthouserc.json"
          temporaryPublicStorage: true
          runs: 1
          urls: |
            http://localhost:1313/
            http://localhost:1313/about
            http://localhost:1313/contact
            http://localhost:1313/thank-you
            http://localhost:1313/web-applications
            http://localhost:1313/websites
            http://localhost:1313/privacy-policy
            http://localhost:1313/terms-and-conditions
      - name: Build Site
        run: hugo --minify
      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@v0.0.2
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: digital-masterpiece