# https://www.jacobtomlinson.co.uk/posts/2020/testing-static-sites-with-lighthouse-ci-and-github-actions/
name: Firebase Deployment & Lighthouse Audit
on:
  push:
    branches:
      - 'master'
jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.69.2"
          extended: true
      - name: Install NPM Dependencies
        run: npm install
      - name: Build Site
        run: hugo --minify
      - name: Setup Node
        uses: actions/setup-node@master
      - name: Optimize SVGs
        run: npm install -g svgo && svgo -r ./public
      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@v0.0.2
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: digital-masterpiece
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: "./.github/config/lighthouserc.json"
          temporaryPublicStorage: true
          runs: 1
          urls: |
            https://www.digital-masterpiece.com/
            https://www.digital-masterpiece.com/about/
            https://www.digital-masterpiece.com/contact/
            https://www.digital-masterpiece.com/thank-you/
            https://www.digital-masterpiece.com/services/
            https://www.digital-masterpiece.com/services/web-applications/
            https://www.digital-masterpiece.com/services/websites/
            https://www.digital-masterpiece.com/privacy-policy/
            https://www.digital-masterpiece.com/terms-and-conditions/