# https://www.jacobtomlinson.co.uk/posts/2020/testing-static-sites-with-lighthouse-ci-and-github-actions/
name: Lighthouse CI
on: push
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.68.3"
          extended: true
      - name: Build site
        run: hugo
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: "./.github/config/lighthouserc.json"