# https://www.jacobtomlinson.co.uk/posts/2020/testing-static-sites-with-lighthouse-ci-and-github-actions/
name: Lighthouse CI
on: push
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.68.3"
          extended: true
      - name: Build site
        run: hugo server --baseURL=http://localhost:1313 &
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: "./.github/config/lighthouserc.json"
          temporaryPublicStorage: true
          urls: |
            http://localhost:1313/
            http://localhost:1313/about
            http://localhost:1313/request-a-quote
            http://localhost:1313/thank-you
            http://localhost:1313/web-applications
            http://localhost:1313/websites